-- Insert Categories
INSERT INTO categories (name, slug, description, parent_id, created_at, updated_at) VALUES
                                                                                        ('Living Room', 'living-room', 'Furniture for living room', NULL, NOW(), NOW()),
                                                                                        ('Bedroom', 'bedroom', 'Furniture for bedroom', NULL, NOW(), NOW()),
                                                                                        ('Dining Room', 'dining-room', 'Furniture for dining room', NULL, NOW(), NOW()),
                                                                                        ('Office', 'office', 'Furniture for office', NULL, NOW(), NOW());

-- Insert Brands
INSERT INTO brands (name, slug, description, logo_url, created_at, updated_at) VALUES
                                                                                   ('NovaWood', 'novawood', 'Premium wood furniture', NULL, NOW(), NOW()),
                                                                                   ('ModernLoft', 'modernloft', 'Modern urban furniture', NULL, NOW(), NOW()),
                                                                                   ('ClassicHome', 'classichome', 'Classic home furniture', NULL, NOW(), NOW());

-- Insert Products
INSERT INTO products (name, slug, description, price, stock, material, color, dimensions, weight, thumbnail_url, category_id, brand_id, created_at, updated_at) VALUES
                                                                                                                                                                    ('Oak Sofa 3-Seater', 'oak-sofa-3-seater', 'Premium oak wood sofa with linen fabric', 1299.00, 15, 'Oak Wood', 'Natural Oak', '220x90x85 cm', 45.0, 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', 1, 1, NOW(), NOW()),
                                                                                                                                                                    ('Minimalist Coffee Table', 'minimalist-coffee-table', 'Clean lines walnut coffee table', 449.00, 20, 'Walnut', 'Dark Walnut', '120x60x45 cm', 18.0, 'https://images.unsplash.com/photo-1611269154421-4e27233ac5c5?w=800', 1, 2, NOW(), NOW()),
                                                                                                                                                                    ('King Bed Frame', 'king-bed-frame', 'Solid oak king size bed frame', 1599.00, 8, 'Oak Wood', 'Natural Oak', '200x180x90 cm', 80.0, 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800', 2, 1, NOW(), NOW()),
                                                                                                                                                                    ('Bedside Table Set', 'bedside-table-set', 'Pair of matching bedside tables', 399.00, 12, 'Oak Wood', 'White Oak', '50x40x55 cm', 12.0, 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800', 2, 3, NOW(), NOW()),
                                                                                                                                                                    ('Dining Table 6-Seater', 'dining-table-6-seater', 'Solid walnut dining table seats 6', 1899.00, 5, 'Walnut', 'Dark Walnut', '180x90x75 cm', 65.0, 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800', 3, 2, NOW(), NOW()),
                                                                                                                                                                    ('Dining Chair Set x4', 'dining-chair-set-x4', 'Set of 4 upholstered dining chairs', 799.00, 10, 'Walnut', 'Cream/Walnut', '45x50x85 cm', 6.0, 'https://images.unsplash.com/photo-1561677978-583a6c4b6a69?w=800', 3, 2, NOW(), NOW()),
                                                                                                                                                                    ('Executive Desk', 'executive-desk', 'Large executive office desk with drawers', 999.00, 7, 'Oak Wood', 'Natural Oak', '160x80x75 cm', 55.0, 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800', 4, 1, NOW(), NOW()),
                                                                                                                                                                    ('Ergonomic Office Chair', 'ergonomic-office-chair', 'Adjustable ergonomic chair for home office', 599.00, 18, 'Metal/Fabric', 'Black', '65x65x110 cm', 14.0, 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800', 4, 3, NOW(), NOW()),
                                                                                                                                                                    ('Bookshelf 5-Tier', 'bookshelf-5-tier', 'Tall 5-tier bookshelf in oak', 349.00, 25, 'Oak Wood', 'Natural Oak', '80x30x180 cm', 22.0, 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800', 4, 1, NOW(), NOW()),
                                                                                                                                                                    ('Lounge Armchair', 'lounge-armchair', 'Comfortable lounge armchair in velvet', 699.00, 14, 'Beech/Velvet', 'Forest Green', '80x85x95 cm', 20.0, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 1, 3, NOW(), NOW());