spring:
  application:
    name: nova-furniture

  datasource:
    url: jdbc:postgresql://localhost:5432/nova_furniture
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /api-docs